### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by pgegenfurtner** [Jonesus/gatsby-source-directus7#3]
I connected the plugin to my directus api and get an error while the plugin is mapping (o2m / m2o) relationships.

Could this happen because not all relationships I defined in directus are filled with data?
The error happens in `process.js` in the `mapRelations` function. The id in line 129 is not defined.

I will try to investigate a bit more.

Error:
```
error Plugin gatsby-source-directus7 returned an error


  TypeError: Cannot read property 'id' of undefined
  
  - process.js:161 mappedEntities.(anonymous function).mappedEntities.(anonymous function).map.entity
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/process.js:161:86
  
  - Array.map
  
  - process.js:159 relations.forEach.relation
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/process.js:159:47
  
  - Array.forEach
  
  - process.js:145 mapRelations
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/process.js:145:13
  
  - gatsby-node.js:70 Object.exports.sourceNodes
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/gatsby-node.js:70:60

```

**Comment by Jonesus** [comment]
Interesting find!

> Could this happen because not all relationships I defined in directus are filled with data? The error happens in process.js in the mapRelations function. The id in line 129 is not defined.

This might very well be the case, it seems I've forgotten to add any proper checks for that. I think though that this shouldn't happen if both collections of the relation are empty as then there would be nothing to map, can you give a sample of the relations and data you currently have?

**Comment by Jonesus** [comment]
> Could this happen because not all relationships I defined in directus are filled with data?

I was able to replicate the exact error by doing this in a test project, I'll try to come up with a proper fix soon-ish and let's hope it works out for you too :)

**Comment by pgegenfurtner** [comment]
Great! 
I found out two more things that might be helpful:
1. in the `directus_relations` table I had some relations with missing data defined. I suspect those were some misconfigurations which did not get deleted. (I removed the rows and the error from above came later)
2. In some translation tables I had data from deleted entries. So so relation could be established. I also removed those rows and the process got even further. Now I'm getting it in m2m relationships. 

I will look further what I can find.

**Comment by Jonesus** [comment]
I pushed a new branch `bugfix/missing-relations-error-handling` to #4 where the original issue seems to be fixed for me, can you try that out and report how it works out for you?

>  I suspect those were some misconfigurations which did not get deleted.

Yeah I've also noticed that Directus doesn't always clean up one's mess if some relations get set up incorrectly and deleted afterwards, but that should probably be set up as a ticket to Directus...

> In some translation tables I had data from deleted entries. So so relation could be established. I also removed those rows and the process got even further. Now I'm getting it in m2m relationships.

So now the error is happening also in M2M? If so then that is weird indeed, are you sure there isn't a misconfiguration on the relation in Directus's end?

**Comment by pgegenfurtner** [comment]
The original issue seems to be solved. 
But now it hangs on the M2M part with the following error:

```
error Plugin gatsby-source-directus7 returned an error


  TypeError: Cannot read property 'map' of undefined

  - process.js:168 relations.forEach.relation
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/process.js:168:47

  - Array.forEach

  - process.js:145 mapRelations
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/process.js:145:13

  - gatsby-node.js:70 Object.exports.sourceNodes
    /Users/pgegenfurtner/Projekte/opensource/gatsby-source-directus7/gatsby-node.js:70:60

```
I don't believe that there is a misconfiguration, but I will investigate.

**Comment by Jonesus** [comment]
Hmm, do you have any more information about the M2M relations you're trying to use, maybe a database dump or something? I can't seem to reproduce that error after setting up a mock M2M as advised [here](https://docs.directus.io/guides/relationships.html#many-to-many) so it's quite hard to try and come up with a solution :sweat_smile:

**Comment by pgegenfurtner** [comment]
The m2m error occurs on relations to directus_files (Files field type). At `mappedEntities[targetCol] = mappedEntities[targetCol].map()` (in the `junctions.forEach()`) the `targetCol` is `directus_files`, which is not present in the `mappedEntries` array.

I tried to setup a sample database for you, but the error does not occur there.
But when I look it up via graphiql, the relation ins not made.

**Comment by trivoallan** [comment]
Hi,

I'm having the same issue.

I exported my test database to https://gist.github.com/trivoallan/eadb627a22dc280f0790db9d99cbcb77 so that you can use it for debuging the issue.

**Comment by Jonesus** [comment]
Thanks a lot @trivoallan!

It seems that at least in your case the error was caused by a broken `directus_relations` item:

```js
{
  id: 28,
  collection_many: 'collection',
  field_many: 'id',
  collection_one: null,
  field_one: null,
  junction_field: null
}
```

Quite likely it's just a leftover from an earlier accidental relation misconfiguration, but Directus doesn't do a good job cleaning them up. I fixed the edge case handling though, as such things shouldn't crash the whole plugin :) I also fixed some semi-related issues that had/could have risen with your scenarios.

Your database dump was essential in debugging the issue! Upgrade the plugin to v0.6.0 in your setup and try it out, everything hopefully works now! There are a few weirdnesses in your `directus_relations` which causes some warnings in the new version, but when I tested them out in GraphiQL all seemed to work correctly!

**Comment by trivoallan** [comment]
Hi,

I confirm version 0.6.0 fixes the problem. Thanks !
Glad the database dump helped.

**Comment by pgegenfurtner** [comment]
I'm still getting the `TypeError: Cannot read property 'map' of undefined` error

**Comment by Jonesus** [comment]
Hi @pgegenfurtner , do you have any chance to give me a database dump or any way to recreate the issue on my own machine? It's the only way I can really help any more...

**Comment by Jonesus** [comment]
Hey @pgegenfurtner ! Sorry for coming back to this issue after such a long time, I've pushed a few releases since this issue and now the latest [v0.8.0](https://github.com/Jonesus/gatsby-source-directus7/releases/tag/v0.8.0) release should at least be working :) Please open a new issue or reopen this one if the problems still persist!
